"""auto-generate from current models

Revision ID: 6bce92fcbe81
Revises: 0001
Create Date: 2026-02-16 09:41:32.875781

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6bce92fcbe81'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_st_anthony_high_school_courses_id', table_name='st_anthony_high_school_courses')
    op.drop_index('ix_st_anthony_high_school_courses_student_id', table_name='st_anthony_high_school_courses')
    op.drop_table('st_anthony_high_school_courses')
    op.drop_index('ix_st_anthony_high_school_students_id', table_name='st_anthony_high_school_students')
    op.drop_index('ix_st_anthony_high_school_students_student_id', table_name='st_anthony_high_school_students')
    op.drop_table('st_anthony_high_school_students')
    op.drop_index('ix_mayfair_high_school_courses_course_id', table_name='mayfair_high_school_courses')
    op.drop_index('ix_mayfair_high_school_courses_id', table_name='mayfair_high_school_courses')
    op.drop_index('ix_mayfair_high_school_courses_student_id', table_name='mayfair_high_school_courses')
    op.drop_index('ix_mayfair_high_school_courses_term_year', table_name='mayfair_high_school_courses')
    op.drop_table('mayfair_high_school_courses')
    op.drop_index('ix_mayfair_high_school_students_id', table_name='mayfair_high_school_students')
    op.drop_index('ix_mayfair_high_school_students_student_id', table_name='mayfair_high_school_students')
    op.drop_table('mayfair_high_school_students')
    op.drop_index('ix_lbusd_courses_course_id', table_name='lbusd_courses')
    op.drop_index('ix_lbusd_courses_id', table_name='lbusd_courses')
    op.drop_index('ix_lbusd_courses_student_id', table_name='lbusd_courses')
    op.drop_index('ix_lbusd_courses_term_year', table_name='lbusd_courses')
    op.drop_table('lbusd_courses')
    op.drop_index('ix_lbusd_students_id', table_name='lbusd_students')
    op.drop_index('ix_lbusd_students_student_id', table_name='lbusd_students')
    op.drop_table('lbusd_students')
    op.alter_column('admission_criteria', 'institution_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index(op.f('ix_admission_criteria_institution_id'), 'admission_criteria', ['institution_id'], unique=False)
    op.create_unique_constraint('uq_admission_criteria_ag', 'admission_criteria', ['institution_id', 'a_to_g_course_type', 'year_intake'])
    op.drop_constraint('admission_criteria_institution_id_fkey', 'admission_criteria', type_='foreignkey')
    op.create_foreign_key(None, 'admission_criteria', 'institution', ['institution_id'], ['id'], ondelete='CASCADE')
    op.alter_column('admission_status', 'status',
               existing_type=postgresql.ENUM('applied', 'under_review', 'admitted', 'waitlisted', 'rejected', name='admission_decision'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('admission_status', 'i20_status',
               existing_type=postgresql.ENUM('not_required', 'pending_documents', 'in_review', 'generated', 'sent', 'expired', name='i20_status'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('admission_status', 'institution_id_applied_for',
               existing_type=sa.BIGINT(),
               nullable=False)
    # Drop foreign key constraints first, then drop and recreate columns
    op.drop_constraint('admission_status_updated_by_profiles_fkey', 'admission_status', type_='foreignkey')
    op.drop_constraint('admission_status_institution_id_applied_for_fkey', 'admission_status', type_='foreignkey')
    # Drop the column and recreate it as BigInteger (UUID cannot be cast to BIGINT)
    op.drop_column('admission_status', 'updated_by')
    op.add_column('admission_status', sa.Column('updated_by', sa.BigInteger(), nullable=True))
    op.drop_index('ix_admission_status_classifier_type_source', table_name='admission_status')
    op.create_index(op.f('ix_admission_status_institution_id_applied_for'), 'admission_status', ['institution_id_applied_for'], unique=False)
    op.create_unique_constraint('uq_student_per_institution', 'admission_status', ['student_id', 'institution_id_applied_for'])
    op.create_foreign_key(None, 'admission_status', 'institution', ['institution_id_applied_for'], ['id'], ondelete='RESTRICT')
    op.drop_column('admission_status', 'classifier_type_source')
    op.alter_column('cloud_file_location', 'institution_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('cloud_file_location', 'sync_status',
               existing_type=postgresql.ENUM('not_configured', 'active', 'syncing', 'paused', 'error', name='cloud_sync_status'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # Drop foreign key constraints first, then drop and recreate columns
    op.drop_constraint('cloud_file_location_updated_by_user_id_profiles_fkey', 'cloud_file_location', type_='foreignkey')
    op.drop_constraint('cloud_file_location_institution_id_fkey', 'cloud_file_location', type_='foreignkey')
    # Drop the column and recreate it as BigInteger (UUID cannot be cast to BIGINT)
    op.drop_column('cloud_file_location', 'updated_by_user_id')
    op.add_column('cloud_file_location', sa.Column('updated_by_user_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_cloud_file_location_institution_id'), 'cloud_file_location', ['institution_id'], unique=False)
    op.create_unique_constraint('uq_cloud_location_active_per_institution', 'cloud_file_location', ['institution_id', 'is_active'])
    op.create_foreign_key(None, 'cloud_file_location', 'institution', ['institution_id'], ['id'], ondelete='CASCADE')
    op.alter_column('extraction_file_details', 'institution_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index(op.f('ix_extraction_file_details_institution_id'), 'extraction_file_details', ['institution_id'], unique=False)
    op.drop_constraint('extraction_file_details_institution_id_fkey', 'extraction_file_details', type_='foreignkey')
    op.create_foreign_key(None, 'extraction_file_details', 'institution', ['institution_id'], ['id'], ondelete='CASCADE')
    op.alter_column('institution', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_institution_id'), 'institution', ['id'], unique=False)
    op.create_index(op.f('ix_institution_institution_name'), 'institution', ['institution_name'], unique=False)
    op.alter_column('otp_challenges', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('otp_challenges', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('otp_challenges', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('otp_challenges', 'first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('otp_challenges', 'last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('otp_challenges', 'institution_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('otp_challenges', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('otp_challenges', 'zip',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('otp_challenges', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('otp_challenges', 'otp_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('otp_challenges', 'attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('otp_challenges', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_otp_challenges_id'), 'otp_challenges', ['id'], unique=True)
    op.alter_column('overall_gpa_criteria', 'institution_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index(op.f('ix_overall_gpa_criteria_institution_id'), 'overall_gpa_criteria', ['institution_id'], unique=False)
    op.create_unique_constraint('uq_overall_gpa_criteria', 'overall_gpa_criteria', ['institution_id', 'year_intake'])
    op.drop_constraint('overall_gpa_criteria_institution_id_fkey', 'overall_gpa_criteria', type_='foreignkey')
    op.create_foreign_key(None, 'overall_gpa_criteria', 'institution', ['institution_id'], ['id'], ondelete='CASCADE')
    op.alter_column('profiles', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('profiles', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('profiles', 'first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('profiles', 'last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('profiles', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('profiles', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('profiles', 'otp_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('profiles', 'otp_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('profiles', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_profiles_institution_id', table_name='profiles')
    op.drop_constraint('profiles_email_key', 'profiles', type_='unique')
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=True)
    op.create_index(op.f('ix_profiles_institution_id'), 'profiles', ['institution_id'], unique=False)
    op.drop_constraint('profiles_institution_id_fkey', 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'institution', ['institution_id'], ['id'], ondelete='SET NULL')
    op.alter_column('program_criteria', 'institution_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # Drop foreign key constraints first, then drop and recreate columns
    op.drop_constraint('program_criteria_updated_by_user_id_profiles_fkey', 'program_criteria', type_='foreignkey')
    op.drop_constraint('program_criteria_institution_id_fkey', 'program_criteria', type_='foreignkey')
    # Drop the column and recreate it as BigInteger (UUID cannot be cast to BIGINT)
    op.drop_column('program_criteria', 'updated_by_user_id')
    op.add_column('program_criteria', sa.Column('updated_by_user_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_program_criteria_institution_id'), 'program_criteria', ['institution_id'], unique=False)
    op.create_unique_constraint('uq_program_criteria', 'program_criteria', ['institution_id', 'program_name', 'year_intake'])
    op.create_foreign_key(None, 'program_criteria', 'institution', ['institution_id'], ['id'], ondelete='CASCADE')
    op.alter_column('templates', 'institution_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # Drop foreign key constraints first, then drop and recreate columns
    op.drop_constraint('templates_updated_by_user_id_profiles_fkey', 'templates', type_='foreignkey')
    op.drop_constraint('templates_institution_id_fkey', 'templates', type_='foreignkey')
    # Drop the column and recreate it as BigInteger (UUID cannot be cast to BIGINT)
    op.drop_column('templates', 'updated_by_user_id')
    op.add_column('templates', sa.Column('updated_by_user_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_templates_institution_id'), 'templates', ['institution_id'], unique=False)
    op.create_unique_constraint('uq_i20_template_active_per_institution', 'templates', ['institution_id', 'is_active'])
    op.create_foreign_key(None, 'templates', 'institution', ['institution_id'], ['id'], ondelete='CASCADE')
    op.drop_index('ix_uc_doorway_courses_course_ag_category_letter', table_name='uc_doorway_courses')
    op.drop_index('ix_uc_course_school_year_ag', table_name='uc_doorway_courses')
    op.create_index('ix_uc_course_school_year_ag', 'uc_doorway_courses', ['school_id', 'academic_year'], unique=False)
    op.drop_column('uc_doorway_courses', 'course_honors')
    op.drop_column('uc_doorway_courses', 'course_transcript_abbrevs')
    op.drop_column('uc_doorway_courses', 'course_ag_category_letter')
    op.drop_column('uc_doorway_courses', 'course_ag_category_name')
    op.drop_column('uc_doorway_courses', 'course_environment')
    op.drop_column('uc_doorway_courses', 'course_grades')
    op.drop_column('uc_doorway_courses', 'course_discipline')
    op.drop_column('uc_doorway_courses', 'course_local_codes')
    op.drop_column('uc_doorway_schools', 'type_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uc_doorway_schools', sa.Column('type_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('uc_doorway_courses', sa.Column('course_local_codes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('uc_doorway_courses', sa.Column('course_discipline', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('uc_doorway_courses', sa.Column('course_grades', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('uc_doorway_courses', sa.Column('course_environment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('uc_doorway_courses', sa.Column('course_ag_category_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('uc_doorway_courses', sa.Column('course_ag_category_letter', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('uc_doorway_courses', sa.Column('course_transcript_abbrevs', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('uc_doorway_courses', sa.Column('course_honors', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index('ix_uc_course_school_year_ag', table_name='uc_doorway_courses')
    op.create_index('ix_uc_course_school_year_ag', 'uc_doorway_courses', ['school_id', 'academic_year', 'course_ag_category_letter'], unique=False)
    op.create_index('ix_uc_doorway_courses_course_ag_category_letter', 'uc_doorway_courses', ['course_ag_category_letter'], unique=False)
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.create_foreign_key('templates_institution_id_fkey', 'templates', 'institution', ['institution_id'], ['id'])
    op.create_foreign_key('templates_updated_by_user_id_profiles_fkey', 'templates', 'profiles', ['updated_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_i20_template_active_per_institution', 'templates', type_='unique')
    op.drop_index(op.f('ix_templates_institution_id'), table_name='templates')
    op.alter_column('templates', 'updated_by_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('templates', 'institution_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'program_criteria', type_='foreignkey')
    op.create_foreign_key('program_criteria_institution_id_fkey', 'program_criteria', 'institution', ['institution_id'], ['id'])
    op.create_foreign_key('program_criteria_updated_by_user_id_profiles_fkey', 'program_criteria', 'profiles', ['updated_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_program_criteria', 'program_criteria', type_='unique')
    op.drop_index(op.f('ix_program_criteria_institution_id'), table_name='program_criteria')
    op.alter_column('program_criteria', 'updated_by_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('program_criteria', 'institution_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key('profiles_institution_id_fkey', 'profiles', 'institution', ['institution_id'], ['id'])
    op.drop_index(op.f('ix_profiles_institution_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.create_unique_constraint('profiles_email_key', 'profiles', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_profiles_institution_id', 'profiles', ['institution_id'], unique=False)
    op.alter_column('profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('profiles', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('profiles', 'otp_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('profiles', 'otp_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('profiles', 'password_hash',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('profiles', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('profiles', 'last_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('profiles', 'first_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('profiles', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('profiles', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'overall_gpa_criteria', type_='foreignkey')
    op.create_foreign_key('overall_gpa_criteria_institution_id_fkey', 'overall_gpa_criteria', 'institution', ['institution_id'], ['id'])
    op.drop_constraint('uq_overall_gpa_criteria', 'overall_gpa_criteria', type_='unique')
    op.drop_index(op.f('ix_overall_gpa_criteria_institution_id'), table_name='overall_gpa_criteria')
    op.alter_column('overall_gpa_criteria', 'institution_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_index(op.f('ix_otp_challenges_id'), table_name='otp_challenges')
    op.alter_column('otp_challenges', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('otp_challenges', 'attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('otp_challenges', 'otp_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('otp_challenges', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('otp_challenges', 'zip',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('otp_challenges', 'city',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('otp_challenges', 'institution_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('otp_challenges', 'last_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('otp_challenges', 'first_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('otp_challenges', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('otp_challenges', 'phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('otp_challenges', 'email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_institution_institution_name'), table_name='institution')
    op.drop_index(op.f('ix_institution_id'), table_name='institution')
    op.alter_column('institution', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'extraction_file_details', type_='foreignkey')
    op.create_foreign_key('extraction_file_details_institution_id_fkey', 'extraction_file_details', 'institution', ['institution_id'], ['id'])
    op.drop_index(op.f('ix_extraction_file_details_institution_id'), table_name='extraction_file_details')
    op.alter_column('extraction_file_details', 'institution_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'cloud_file_location', type_='foreignkey')
    op.create_foreign_key('cloud_file_location_institution_id_fkey', 'cloud_file_location', 'institution', ['institution_id'], ['id'])
    op.create_foreign_key('cloud_file_location_updated_by_user_id_profiles_fkey', 'cloud_file_location', 'profiles', ['updated_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_cloud_location_active_per_institution', 'cloud_file_location', type_='unique')
    op.drop_index(op.f('ix_cloud_file_location_institution_id'), table_name='cloud_file_location')
    op.alter_column('cloud_file_location', 'updated_by_user_id',
               existing_type=sa.BigInteger(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('cloud_file_location', 'sync_status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('not_configured', 'active', 'syncing', 'paused', 'error', name='cloud_sync_status'),
               existing_nullable=False)
    op.alter_column('cloud_file_location', 'institution_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.add_column('admission_status', sa.Column('classifier_type_source', postgresql.ENUM('mayfair_high_school', 'lbusd', 'st_anthony_high_school', name='student_source'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'admission_status', type_='foreignkey')
    op.create_foreign_key('admission_status_institution_id_applied_for_fkey', 'admission_status', 'institution', ['institution_id_applied_for'], ['id'])
    op.create_foreign_key('admission_status_updated_by_profiles_fkey', 'admission_status', 'profiles', ['updated_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint('uq_student_per_institution', 'admission_status', type_='unique')
    op.drop_index(op.f('ix_admission_status_institution_id_applied_for'), table_name='admission_status')
    op.create_index('ix_admission_status_classifier_type_source', 'admission_status', ['classifier_type_source'], unique=False)
    op.alter_column('admission_status', 'updated_by',
               existing_type=sa.BigInteger(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('admission_status', 'institution_id_applied_for',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('admission_status', 'i20_status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('not_required', 'pending_documents', 'in_review', 'generated', 'sent', 'expired', name='i20_status'),
               existing_nullable=False)
    op.alter_column('admission_status', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('applied', 'under_review', 'admitted', 'waitlisted', 'rejected', name='admission_decision'),
               existing_nullable=False)
    op.drop_constraint(None, 'admission_criteria', type_='foreignkey')
    op.create_foreign_key('admission_criteria_institution_id_fkey', 'admission_criteria', 'institution', ['institution_id'], ['id'])
    op.drop_constraint('uq_admission_criteria_ag', 'admission_criteria', type_='unique')
    op.drop_index(op.f('ix_admission_criteria_institution_id'), table_name='admission_criteria')
    op.alter_column('admission_criteria', 'institution_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.create_table('lbusd_students',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('school_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('home_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('counselor_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_gpa_course', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('aca_gpa_course', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('university_gpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('enter_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('graduation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('state_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lbusd_students_pkey')
    )
    op.create_index('ix_lbusd_students_student_id', 'lbusd_students', ['student_id'], unique=False)
    op.create_index('ix_lbusd_students_id', 'lbusd_students', ['id'], unique=False)
    op.create_table('lbusd_courses',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('credit_attempted_completed', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mark', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('term_schoolname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('term_grade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('term_month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('term_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_credit_attempted', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_credit_completed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_gpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lbusd_courses_pkey')
    )
    op.create_index('ix_lbusd_courses_term_year', 'lbusd_courses', ['term_year'], unique=False)
    op.create_index('ix_lbusd_courses_student_id', 'lbusd_courses', ['student_id'], unique=False)
    op.create_index('ix_lbusd_courses_id', 'lbusd_courses', ['id'], unique=False)
    op.create_index('ix_lbusd_courses_course_id', 'lbusd_courses', ['course_id'], unique=False)
    op.create_table('mayfair_high_school_students',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('school_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('home_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('counselor_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cumulative_gpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('enter_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('graduation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('grade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mayfair_high_school_students_pkey')
    )
    op.create_index('ix_mayfair_high_school_students_student_id', 'mayfair_high_school_students', ['student_id'], unique=False)
    op.create_index('ix_mayfair_high_school_students_id', 'mayfair_high_school_students', ['id'], unique=False)
    op.create_table('mayfair_high_school_courses',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('credit_attempted_completed', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('mark', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('term_schoolname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('term_grade', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('term_month', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('term_year', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('total_credit_attempted', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_credit_completed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_gpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mayfair_high_school_courses_pkey')
    )
    op.create_index('ix_mayfair_high_school_courses_term_year', 'mayfair_high_school_courses', ['term_year'], unique=False)
    op.create_index('ix_mayfair_high_school_courses_student_id', 'mayfair_high_school_courses', ['student_id'], unique=False)
    op.create_index('ix_mayfair_high_school_courses_id', 'mayfair_high_school_courses', ['id'], unique=False)
    op.create_index('ix_mayfair_high_school_courses_course_id', 'mayfair_high_school_courses', ['course_id'], unique=False)
    op.create_table('st_anthony_high_school_students',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('school_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('home_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('enter_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('graduation_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('total_units_earned', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cumulative_gpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='st_anthony_high_school_students_pkey')
    )
    op.create_index('ix_st_anthony_high_school_students_student_id', 'st_anthony_high_school_students', ['student_id'], unique=False)
    op.create_index('ix_st_anthony_high_school_students_id', 'st_anthony_high_school_students', ['id'], unique=False)
    op.create_table('st_anthony_high_school_courses',
    sa.Column('id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sem_1', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sem_2', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('s_sch', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sem_year', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('sem_school_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_units_earned', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cumulative_gpa', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='st_anthony_high_school_courses_pkey')
    )
    op.create_index('ix_st_anthony_high_school_courses_student_id', 'st_anthony_high_school_courses', ['student_id'], unique=False)
    op.create_index('ix_st_anthony_high_school_courses_id', 'st_anthony_high_school_courses', ['id'], unique=False)
    # ### end Alembic commands ###

